apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-proxy
  labels:
    app: rest-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rest-proxy
    spec:
      containers:
      - name: rest-proxy
        image: mesosphere/cp-kafka-rest:5.3.0
        command: ["/etc/confluent/docker/run"]
        resources:
          requests:
            memory: {{ .Params.MEMORY }}
            cpu: {{ .Params.CPUS }}
          limits:
            memory: {{ .Params.MEM_LIMIT }}
            cpu: {{ .Params.CPUS_LIMIT }}
        ports:
        - containerPort: 8082
          name: rest-proxy
        volumeMounts:
        - name: rp-persistent-storage
          mountPath: /var/lib/rest-proxy
        env:
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL 
          value: {{ .Params.SCHEMA_REGISTRY_URL }}
        - name: KAFKA_REST_HOST_NAME
          value: {{ .Params.HOST_NAME }}
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: "kafka-kafka-0.kafka-svc.default.svc.cluster.local:9093,kafka-kafka-1.kafka-svc.default.svc.cluster.local:9093,kafka-kafka-2.kafka-svc.default.svc.cluster.local:9093"
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            path: /
            port: 8082
      volumes:
      - name: rp-persistent-storage
        persistentVolumeClaim:
          claimName: rest-proxy-pv
